"""moving to func nowww

Revision ID: 10e898c15848
Revises: 5e87a0bc087e
Create Date: 2025-05-15 12:49:03.483261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10e898c15848'
down_revision: Union[str, None] = '5e87a0bc087e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_published', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('person', 'date_publoshed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_publoshed', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('person', 'date_published')
    # ### end Alembic commands ###
