"""upgraded title meta

Revision ID: 37d991f4a9ef
Revises: 0264e88212f4
Create Date: 2025-05-11 09:49:22.485237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d991f4a9ef'
down_revision: Union[str, None] = '0264e88212f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_meta', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('title_meta', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('title_meta', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.drop_constraint('title_meta_artist_fkey', 'title_meta', type_='foreignkey')
    op.drop_constraint('title_meta_publisher_fkey', 'title_meta', type_='foreignkey')
    op.drop_constraint('title_meta_author_fkey', 'title_meta', type_='foreignkey')
    op.create_foreign_key(None, 'title_meta', 'person', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'title_meta', 'person', ['publisher_id'], ['id'])
    op.create_foreign_key(None, 'title_meta', 'person', ['author_id'], ['id'])
    op.drop_column('title_meta', 'publisher')
    op.drop_column('title_meta', 'artist')
    op.drop_column('title_meta', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_meta', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('title_meta', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('title_meta', sa.Column('publisher', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'title_meta', type_='foreignkey')
    op.drop_constraint(None, 'title_meta', type_='foreignkey')
    op.drop_constraint(None, 'title_meta', type_='foreignkey')
    op.create_foreign_key('title_meta_author_fkey', 'title_meta', 'person', ['author'], ['id'])
    op.create_foreign_key('title_meta_publisher_fkey', 'title_meta', 'person', ['publisher'], ['id'])
    op.create_foreign_key('title_meta_artist_fkey', 'title_meta', 'person', ['artist'], ['id'])
    op.drop_column('title_meta', 'publisher_id')
    op.drop_column('title_meta', 'artist_id')
    op.drop_column('title_meta', 'author_id')
    # ### end Alembic commands ###
