"""moving to func now

Revision ID: 5e87a0bc087e
Revises: def3cc47280b
Create Date: 2025-05-15 12:40:13.863005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e87a0bc087e'
down_revision: Union[str, None] = 'def3cc47280b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_publoshed', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('person', 'date_published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_published', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('person', 'date_publoshed')
    # ### end Alembic commands ###
