"""Updated translate_team member

Revision ID: 709336ccee3f
Revises: 1241cf081b3e
Create Date: 2025-05-05 21:16:12.312845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709336ccee3f'
down_revision: Union[str, None] = '1241cf081b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate_team_member', sa.Column('accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translate_team_member', 'accepted')
    # ### end Alembic commands ###
