"""Translate team: alot of changes

Revision ID: 7e630b7c819c
Revises: aeb97259759e
Create Date: 2025-05-25 11:50:01.477379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e630b7c819c'
down_revision: Union[str, None] = 'aeb97259759e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate_team', sa.Column('pfp', sa.LargeBinary(), nullable=True))
    op.drop_column('translate_team', 'fhd')
    op.drop_column('translate_team', 'sd')
    op.drop_column('translate_team', 'hd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate_team', sa.Column('hd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('translate_team', sa.Column('sd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('translate_team', sa.Column('fhd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('translate_team', 'pfp')
    # ### end Alembic commands ###
