"""PageAsset: changed from path to bytes

Revision ID: 7fb440b7e45a
Revises: 7e630b7c819c
Create Date: 2025-05-25 16:55:54.726202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb440b7e45a'
down_revision: Union[str, None] = '7e630b7c819c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_asset', sa.Column('content', sa.LargeBinary(), nullable=False))
    op.drop_constraint('page_asset_translate_team_id_fkey', 'page_asset', type_='foreignkey')
    op.drop_column('page_asset', 'translate_team_id')
    op.drop_column('page_asset', 'asset_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_asset', sa.Column('asset_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('page_asset', sa.Column('translate_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('page_asset_translate_team_id_fkey', 'page_asset', 'translate_team', ['translate_team_id'], ['id'])
    op.drop_column('page_asset', 'content')
    # ### end Alembic commands ###
