"""updated tranlate models

Revision ID: 8b0377d7957b
Revises: bf93904bcc27
Create Date: 2025-05-05 19:53:52.119137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0377d7957b'
down_revision: Union[str, None] = 'bf93904bcc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titlecover', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('translate_team', sa.Column('description', sa.String(), nullable=True))
    op.add_column('translate_team', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('translate_team', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('translate_team', sa.Column('date_approved', sa.DateTime(), nullable=True))
    op.add_column('translate_team', sa.Column('user_approved', sa.String(), nullable=True))
    op.add_column('translate_team', sa.Column('fhd', sa.String(), nullable=True))
    op.add_column('translate_team', sa.Column('hd', sa.String(), nullable=True))
    op.add_column('translate_team', sa.Column('sd', sa.String(), nullable=True))
    op.create_foreign_key(None, 'translate_team', 'user', ['user_approved'], ['uuid'])
    op.drop_column('translate_team', 'pfp')
    op.create_unique_constraint(None, 'translate_team_member', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translate_team_member', type_='unique')
    op.add_column('translate_team', sa.Column('pfp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'translate_team', type_='foreignkey')
    op.drop_column('translate_team', 'sd')
    op.drop_column('translate_team', 'hd')
    op.drop_column('translate_team', 'fhd')
    op.drop_column('translate_team', 'user_approved')
    op.drop_column('translate_team', 'date_approved')
    op.drop_column('translate_team', 'date_created')
    op.drop_column('translate_team', 'approved')
    op.drop_column('translate_team', 'description')
    op.drop_column('titlecover', 'approved')
    # ### end Alembic commands ###
