"""moving to func nowwwwwwwwwww

Revision ID: 9b9a77f70c40
Revises: 2c4578ff4c19
Create Date: 2025-05-15 19:01:24.038347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9a77f70c40'
down_revision: Union[str, None] = '2c4578ff4c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personmeta', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personmeta', 'created_at')
    # ### end Alembic commands ###
