"""added assets rows

Revision ID: a55dfd6f27a4
Revises: a7cbf79e5c14
Create Date: 2025-05-19 17:22:10.133463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55dfd6f27a4'
down_revision: Union[str, None] = 'a7cbf79e5c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_back',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_pfp',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('person_cover',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_user_uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_user_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tranlate_team_pfp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translate_team_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['translate_team_id'], ['translate_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('title_cover', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.drop_constraint('title_cover_created_user_uuid_fkey', 'title_cover', type_='foreignkey')
    op.drop_column('title_cover', 'sd')
    op.drop_column('title_cover', 'hd')
    op.drop_column('title_cover', 'created_user_uuid')
    op.drop_column('title_cover', 'fhd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_cover', sa.Column('fhd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('title_cover', sa.Column('created_user_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('title_cover', sa.Column('hd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('title_cover', sa.Column('sd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('title_cover_created_user_uuid_fkey', 'title_cover', 'user', ['created_user_uuid'], ['uuid'])
    op.drop_column('title_cover', 'data')
    op.drop_table('tranlate_team_pfp')
    op.drop_table('person_cover')
    op.drop_table('user_pfp')
    op.drop_table('user_back')
    # ### end Alembic commands ###
