"""renamed person fields

Revision ID: a7cbf79e5c14
Revises: 9b9a77f70c40
Create Date: 2025-05-16 17:37:24.919358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7cbf79e5c14'
down_revision: Union[str, None] = '9b9a77f70c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column(
        'user_published_uuid', sa.String(), nullable=True))
    op.execute('UPDATE person SET user_published_uuid = user_published')
    op.alter_column('person', 'user_published_uuid', nullable=False)
    op.add_column('person', sa.Column('created_at', sa.DateTime(),
                  server_default=sa.text('NOW()'), nullable=False))
    op.drop_constraint('person_user_published_fkey',
                       'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'user', [
                          'user_published_uuid'], ['uuid'])
    op.drop_column('person', 'user_published')
    op.drop_column('person', 'date_published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_published', postgresql.TIMESTAMP(
    ), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('user_published',
                  sa.VARCHAR(), autoincrement=False, nullable=False))
    op.execute('UPDATE person SET user_published = user_published_uuid')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key('person_user_published_fkey',
                          'person', 'user', ['user_published'], ['uuid'])
    op.drop_column('person', 'created_at')
    op.drop_column('person', 'user_published_uuid')
    # ### end Alembic commands ###
