"""Title view: added title_id foreign key

Revision ID: aeb97259759e
Revises: 16a2897fa772
Create Date: 2025-05-24 09:59:52.423882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb97259759e'
down_revision: Union[str, None] = '16a2897fa772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_meta', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('title_view', sa.Column('title_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'title_view', 'title', ['title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'title_view', type_='foreignkey')
    op.drop_column('title_view', 'title_id')
    op.drop_column('title_meta', 'release_year')
    # ### end Alembic commands ###
