"""initial

Revision ID: dd0e9ae899cb
Revises: 
Create Date: 2025-05-03 20:22:15.122889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd0e9ae899cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_sender',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notification', sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('notification', 'target')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notification', 'value')
    op.drop_table('notification_sender')
    # ### end Alembic commands ###
