"""upgraded title read pos

Revision ID: e3c2b9d93059
Revises: c743d0ce4665
Create Date: 2025-05-11 10:16:38.043340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3c2b9d93059'
down_revision: Union[str, None] = 'c743d0ce4665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_cover', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('title_read_position', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('title_read_position', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_read_position', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('title_read_position', 'created_at')
    op.drop_column('title_cover', 'order')
    # ### end Alembic commands ###
