GENRES_DATA = {
    "target_class": "Genre",
    "data": [
        {"ru": "Арт", "en": "Art"},
        {"ru": "Безумие", "en": "Madness"},
        {"ru": "Боевик", "en": "Action"},
        {"ru": "Боевые искусства", "en": "Martial arts"},
        {"ru": "Вампиры", "en": "Vampires"},
        {"ru": "Военное", "en": "War"},
        {"ru": "Гарем", "en": "Harem"},
        {"ru": "Гендерная интрига", "en": "Gender intrigue"},
        {"ru": "Героическое фентези", "en": "Heroic fantasy"},
        {"ru": "Демоны", "en": "Demons"},
        {"ru": "Детектив", "en": "Detective"},
        {"ru": "Детское", "en": "Children's"},
        {"ru": "Дзёсай", "en": "Josai"},
        {"ru": "Драма", "en": "Drama"},
        {"ru": "Игра", "en": "Game"},
        {"ru": "Исекай", "en": "Isekai"},
        {"ru": "История", "en": "History"},
        {"ru": "Киберпанк", "en": "Cyberpunk"},
        {"ru": "Кодомо", "en": "Kodomo"},
        {"ru": "Комедия", "en": "Comedy"},
        {"ru": "Космос", "en": "Space"},
        {"ru": "Магия", "en": "Magic"},
        {"ru": "Махо-сёдзё", "en": "Maho-shoujo"},
        {"ru": "Машины", "en": "Cars"},
        {"ru": "Меха", "en": "Mecha"},
        {"ru": "Мистика", "en": "Mysticism"},
        {"ru": "Музыка", "en": "Music"},
        {"ru": "Научная фантастика", "en": "Sci-fi"},
        {"ru": "Омегаверс", "en": "Omegaverse"},
        {"ru": "Пародия", "en": "Parody"},
        {"ru": "Повседневность", "en": "Everyday life"},
        {"ru": "Полиция", "en": "Police"},
        {"ru": "Постапокалиптика", "en": "Post-apocalyptic"},
        {"ru": "Приключения", "en": "Adventure"},
        {"ru": "Психология", "en": "Psychology"},
        {"ru": "Романтика", "en": "Romance"},
        {"ru": "Самурайский боевик", "en": "Samurai action"},
        {"ru": "Сверхъестественное", "en": "Supernatural"},
        {"ru": "Сёдзё", "en": "Shoujo"},
        {"ru": "Сёдзё-ай", "en": "Shoujo-ai"},
        {"ru": "Сёнен", "en": "Shonen"},
        {"ru": "Сёнен-ай", "en": "Shonen-ai"},
        {"ru": "Спорт", "en": "Sports"},
        {"ru": "Супер сила", "en": "Super power"},
        {"ru": "Сэйнен", "en": "Seinen"},
        {"ru": "Трагедия", "en": "Tragedy"},
        {"ru": "Триллер", "en": "Thriller"},
        {"ru": "Ужасы", "en": "Horror"},
        {"ru": "Фантастика", "en": "Sci-Fi"},
        {"ru": "Фэнтези", "en": "Fantasy"},
        {"ru": "Школа", "en": "School"},
        {"ru": "Этти", "en": "Ecchi"},
        {"ru": "Юри", "en": "Yuri"},
    ],
}
