TAGS_DATA = {
    "target_class": "Tag",
    "data": [
        {"ru": "18+", "en": "18+"},
        {"ru": "16+", "en": "16+"},
        {"ru": "12+", "en": "12+"},
        {"ru": "0+", "en": "0+"},
        {"ru": "Манга", "en": "Manga"},
        {"ru": "Манхва", "en": "Manhva"},
        {"ru": "Маньхуа", "en": "Manhua"},
        {"ru": "Азартные игры", "en": "Gambling"},
        {"ru": "Алхимия", "en": "Alchemy"},
        {"ru": "Амнезия / Потеря памяти", "en": "Amnesia / Memory Loss"},
        {"ru": "Ангелы", "en": "Angels"},
        {"ru": "Антигерой", "en": "Antihero"},
        {"ru": "Антиутопия", "en": "Dystopia"},
        {"ru": "Апокалипсис", "en": "Apocalypse"},
        {"ru": "Армия", "en": "Army"},
        {"ru": "Артефакты", "en": "Artifacts"},
        {"ru": "Боги", "en": "Gods"},
        {"ru": "Бои на мечах", "en": "Sword Fighting"},
        {"ru": "Борьба за власть", "en": "Power Struggle"},
        {"ru": "Брат и сестра", "en": "Brother and Sister"},
        {"ru": "Будущее", "en": "Future"},
        {"ru": "Ведьма", "en": "Witch"},
        {"ru": "Вестерн", "en": "Western"},
        {"ru": "Видеоигры", "en": "Video Games"},
        {"ru": "Виртуальная реальность", "en": "Virtual Reality"},
        {"ru": "Владыка демонов", "en": "Demon Lord"},
        {"ru": "Военные", "en": "Military"},
        {"ru": "Война", "en": "War"},
        {"ru": "Волшебники / маги", "en": "Wizards / Mages"},
        {"ru": "Волшебные существа", "en": "Magical Creatures"},
        {"ru": "Воспоминания из другого мира", "en": "Memories from Another World"},
        {"ru": "Выживание", "en": "Survival"},
        {"ru": "ГГ женщина", "en": "Female MC"},
        {"ru": "ГГ имба", "en": "IMBA MC"},
        {"ru": "ГГ мужчина", "en": "Male MC"},
        {"ru": "Геймеры", "en": "Gamers"},
        {"ru": "Гильдии", "en": "Guilds"},
        {"ru": "Глупый ГГ", "en": "Stupid MC"},
        {"ru": "Гоблины", "en": "Goblins"},
        {"ru": "Горничные", "en": "Maids"},
        {"ru": "Гяру", "en": "Gyaru"},
        {"ru": "Демоны", "en": "Demons"},
        {"ru": "Драконы", "en": "Dragons"},
        {"ru": "Дружба", "en": "Friendship"},
        {"ru": "Жестокий мир", "en": "Cruel World"},
        {"ru": "Животные компаньоны", "en": "Animal Companions"},
        {"ru": "Завоевание мира", "en": "Conquest world"},
        {"ru": "Зверолюди", "en": "Beastmen"},
        {"ru": "Злые духи", "en": "Evil spirits"},
        {"ru": "Зомби", "en": "Zombies"},
        {"ru": "Игровые элементы", "en": "Game elements"},
        {"ru": "Империи", "en": "Empires"},
        {"ru": "Камера", "en": "Camera"},
        {"ru": "Квесты", "en": "Quests"},
        {"ru": "Космос", "en": "Space"},
        {"ru": "Кулинария", "en": "Cooking"},
        {"ru": "Культивация", "en": "Cultivation"},
        {"ru": "Легендарное оружие", "en": "Legendary weapons"},
        {"ru": "Лоли", "en": "Loli"},
        {"ru": "Магическая академия", "en": "Magic academy"},
        {"ru": "Магия", "en": "Magick"},
        {"ru": "Мафия", "en": "Mafia"},
        {"ru": "Медицина", "en": "Medicine"},
        {"ru": "Месть", "en": "Revenge"},
        {"ru": "Монстродевушки", "en": "Monster girls"},
        {"ru": "Монстры", "en": "Monsters"},
        {"ru": "Музыка", "en": "Music"},
        {"ru": "Навыки / способности", "en": "Skills / abilities"},
        {"ru": "Насилие / жестокость", "en": "Violence / cruelty"},
        {"ru": "Наёмники", "en": "Mercenaries"},
        {"ru": "Нежить", "en": "Undead"},
        {"ru": "Ниндзя", "en": "Ninja"},
        {"ru": "Обмен телами", "en": "Body swap"},
        {"ru": "Обратный Гарем", "en": "Reverse Harem"},
        {"ru": "Огнестрельное оружие", "en": "Firearms"},
        {"ru": "Офисные Работники", "en": "Office workers"},
        {"ru": "Пародия", "en": "Parody"},
        {"ru": "Пираты", "en": "Pirates"},
        {"ru": "Подземелья", "en": "Dungeons"},
        {"ru": "Политика", "en": "Politics"},
        {"ru": "Полиция", "en": "Police"},
        {"ru": "Преступники / Криминал", "en": "Criminals / Crime"},
        {"ru": "Призраки / Духи", "en": "Ghosts / Spirits"},
        {"ru": "Путешествие во времени", "en": "Time travel"},
        {"ru": "Рабы", "en": "Slaves"},
        {"ru": "Разумные расы", "en": "Intelligent races"},
        {"ru": "Ранги силы", "en": "Power ranks"},
        {"ru": "Реинкарнация", "en": "Reincarnation"},
        {"ru": "Роботы", "en": "Robots"},
        {"ru": "Рыцари ", "en": "Knights"},
        {"ru": "Самураи", "en": "Samurai"},
        {"ru": "Система", "en": "System"},
        {"ru": "Скрытие личности", "en": "Identity hiding"},
        {"ru": "Спасение мира", "en": "Saving the world"},
        {"ru": "Спортивное тело", "en": "Sports body"},
        {"ru": "Средневековье", "en": "Middle Ages"},
        {"ru": "Стимпанк", "en": "Steampunk"},
        {"ru": "Супергерои", "en": "Superheroes"},
        {"ru": "Традиционные игры", "en": "Traditional games"},
        {"ru": "Умный ГГ", "en": "Smart MC"},
        {"ru": "Учитель  / ученик", "en": "Teacher / student"},
        {"ru": "Философия", "en": "Philosophy"},
        {"ru": "Хиккикомори", "en": "Hikkikomori"},
        {"ru": "Холодное оружие", "en": "Cold weapons"},
        {"ru": "Шантаж", "en": "Blackmail"},
        {"ru": "Эльфы", "en": "Elves"},
        {"ru": "Якудза", "en": "Yakuza"},
        {"ru": "Яндере", "en": "Yandere"},
        {"ru": "Япония", "en": "Japan"},
    ],
}
