COMMENT_MIN_LENGTH = 1
COMMENT_MAX_LENGTH = 200

USERNAME_MIN_LENGTH = 5
USERNAME_MAX_LENGTH = 20

NICKNAME_MIN_LENGTH = 4
NICKNAME_MAX_LENGTH = 30

USER_STATUS_MIN_LENGTH = 0
USER_STATUS_MAX_LENGTH = 30

USER_ABOUT_MIN_LENGTH = 0
USER_ABOUT_MAX_LENGTH = 300

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 30

USER_ASSETS_DIRECTORY = 'assets/user' # pfp
TITLE_ASSETS_DIRECTORY = 'assets/title' # manga, mahua, etc.
PERSON_ASSETS_DIRECTORY = 'assets/person' # author, artist, publisher
ASSETS_DIRECTORY = 'assets'

ASSETS_PFP_GEOMETRY = (800, 800) # user/person profile picture geometry
ASSETS_COVER_GEOMETRY = (520, 728) # title cover

PENDING_META_LIMIT = 50