COMMENT_LENGTH_RANGE = (1, 200)

USERNAME_LENGTH_RANGE = (4, 14)
PASSWORD_LENGTH_RANGE = (8, 30)

NICKNAME_LENGTH_RANGE = (4, 14)
USER_STATUS_LENGTH_RANGE = (0, 30)
USER_ABOUT_LENGTH_RANGE = (0, 300)

USER_ASSETS_DIRECTORY = 'assets/user' # pfp
TITLE_ASSETS_DIRECTORY = 'assets/title' # manga, mahua, etc.
PERSON_ASSETS_DIRECTORY = 'assets/person' # author, artist, publisher
ASSETS_DIRECTORY = 'assets'

ASSETS_PFP_GEOMETRY = (800, 800) # user/person profile picture geometry
ASSETS_COVER_GEOMETRY = (520, 728) # title cover

PENDING_META_LIMIT = 50