COMMENT_RANGE = (1, 200)
USERNAME_RANGE = (4, 20)
NICKNAME_RANGE = (4, 20)
USER_STATUS_RANGE = (0, 20)
USER_ABOUT_RANGE = (0, 300)
PASSWORD_RANGE = (8, 30)

UHD_PFP_GEOMETRY = (1920, 1920)
UHD_COVER_GEOMETRY = (1920, 2688)
HD_PFP_GEOMETRY = (1280, 1280)
HD_COVER_GEOMETRY = (1280, 1792)
SD_PFP_GEOMETRY = (640, 640)
SD_COVER_GEOMETRY = (640, 896)

TITLE_PENDING_META_LIMIT = 50
PERSON_PENDING_META_LIMIT = 50

ASSETS_DIR = '/home/prepodobnuy/.sdc/Documents/Projects/manga-proj/manga-server/assets'
DEFAULT_PFP = '/home/prepodobnuy/.sdc/Documents/Projects/manga-proj/manga-server/default_pfp.jpg'
DEFAULT_COVER = '/home/prepodobnuy/.sdc/Documents/Projects/manga-proj/manga-server/default_cover.jpg'
DB_URL = 'sqlite:///testdb.db'

def is_string_len_valid(string: str, range: tuple[int, int]) -> bool:
    return range[0] < len(string) < range[1]

def clamp(number: int | float, range: tuple[int | float, int | float]) -> int | float:
    return max(range[0], min(range[1], number))

tags = [
    {"id": 0  , "ru":"Азартные игры", "en":"Gambling"},
    {"id": 1  , "ru":"Алхимия", "en":"Alchemy"},
    {"id": 2  , "ru":"Амнезия / Потеря памяти", "en":"Amnesia / Memory Loss"},
    {"id": 3  , "ru":"Ангелы", "en":"Angels"},
    {"id": 4  , "ru":"Антигерой", "en":"Antihero"},
    {"id": 5  , "ru":"Антиутопия", "en":"Dystopia"},
    {"id": 6  , "ru":"Апокалипсис", "en":"Apocalypse"},
    {"id": 7  , "ru":"Армия", "en":"Army"},
    {"id": 8  , "ru":"Артефакты", "en":"Artifacts"},
    {"id": 9  , "ru":"Боги", "en":"Gods"},
    {"id": 10 , "ru":"Бои на мечах", "en":"Sword Fighting"},
    {"id": 11 , "ru":"Борьба за власть", "en":"Power Struggle"},
    {"id": 12 , "ru":"Брат и сестра", "en":"Brother and Sister"},
    {"id": 13 , "ru":"Будущее", "en":"Future"},
    {"id": 14 , "ru":"Ведьма", "en":"Witch"},
    {"id": 15 , "ru":"Вестерн", "en":"Western"},
    {"id": 16 , "ru":"Видеоигры", "en":"Video Games"},
    {"id": 17 , "ru":"Виртуальная реальность", "en":"Virtual Reality"},
    {"id": 18 , "ru":"Владыка демонов", "en":"Demon Lord"},
    {"id": 19 , "ru":"Военные", "en":"Military"},
    {"id": 20 , "ru":"Война", "en":"War"},
    {"id": 21 , "ru":"Волшебники / маги", "en":"Wizards / Mages"},
    {"id": 22 , "ru":"Волшебные существа", "en":"Magical Creatures"},
    {"id": 23 , "ru":"Воспоминания из другого мира", "en":"Memories from Another World"},
    {"id": 24 , "ru":"Выживание", "en":"Survival"},
    {"id": 25 , "ru":"ГГ женщина", "en":"Female MC"},
    {"id": 26 , "ru":"ГГ имба", "en":"IMBA MC"},
    {"id": 27 , "ru":"ГГ мужчина", "en":"Male MC"},
    {"id": 28 , "ru":"Геймеры", "en":"Gamers"},
    {"id": 29 , "ru":"Гильдии", "en":"Guilds"},
    {"id": 30 , "ru":"Глупый ГГ", "en":"Stupid MC"},
    {"id": 31 , "ru":"Гоблины", "en":"Goblins"},
    {"id": 32 , "ru":"Горничные", "en":"Maids"},
    {"id": 33 , "ru":"Гяру", "en":"Gyaru"},
    {"id": 34 , "ru":"Демоны", "en":"Demons"},
    {"id": 35 , "ru":"Драконы", "en":"Dragons"},
    {"id": 36 , "ru":"Дружба", "en":"Friendship"},
    {"id": 37 , "ru":"Жестокий мир", "en":"Cruel World"},
    {"id": 38 , "ru":"Животные компаньоны", "en":"Animal Companions"},
    {"id": 39 , "ru":"Завоевание мира", "en":"Conquest world"},
    {"id": 40 , "ru":"Зверолюди", "en":"Beastmen"},
    {"id": 41 , "ru":"Злые духи", "en":"Evil spirits"},
    {"id": 42 , "ru":"Зомби", "en":"Zombies"},
    {"id": 43 , "ru":"Игровые элементы", "en":"Game elements"},
    {"id": 44 , "ru":"Империи", "en":"Empires"},
    {"id": 45 , "ru":"Камера", "en":"Camera"},
    {"id": 46 , "ru":"Квесты", "en":"Quests"},
    {"id": 47 , "ru":"Космос", "en":"Space"},
    {"id": 48 , "ru":"Кулинария", "en":"Cooking"},
    {"id": 49 , "ru":"Культивация", "en":"Cultivation"},
    {"id": 50 , "ru":"Легендарное оружие", "en":"Legendary weapons"},
    {"id": 51 , "ru":"Лоли", "en":"Loli"},
    {"id": 52 , "ru":"Магическая академия", "en":"Magic academy"},
    {"id": 53 , "ru":"Магия", "en":"Magick"},
    {"id": 54 , "ru":"Мафия", "en":"Mafia"},
    {"id": 55 , "ru":"Медицина", "en":"Medicine"},
    {"id": 56 , "ru":"Месть", "en":"Revenge"},
    {"id": 57 , "ru":"Монстродевушки", "en":"Monster girls"},
    {"id": 58 , "ru":"Монстры", "en":"Monsters"},
    {"id": 59 , "ru":"Музыка", "en":"Music"},
    {"id": 60 , "ru":"Навыки / способности", "en":"Skills / abilities"},
    {"id": 61 , "ru":"Насилие / жестокость", "en":"Violence / cruelty"},
    {"id": 62 , "ru":"Наёмники", "en":"Mercenaries"},
    {"id": 63 , "ru":"Нежить", "en":"Undead"},
    {"id": 64 , "ru":"Ниндзя", "en":"Ninja"},
    {"id": 65 , "ru":"Обмен телами", "en":"Body swap"},
    {"id": 66 , "ru":"Обратный Гарем", "en":"Reverse Harem"},
    {"id": 67 , "ru":"Огнестрельное оружие", "en":"Firearms"},
    {"id": 68 , "ru":"Офисные Работники", "en":"Office workers"},
    {"id": 69 , "ru":"Пародия", "en":"Parody"},
    {"id": 70 , "ru":"Пираты", "en":"Pirates"},
    {"id": 71 , "ru":"Подземелья", "en":"Dungeons"},
    {"id": 72 , "ru":"Политика", "en":"Politics"},
    {"id": 73 , "ru":"Полиция", "en":"Police"},
    {"id": 74 , "ru":"Преступники / Криминал", "en":"Criminals / Crime"},
    {"id": 75 , "ru":"Призраки / Духи", "en":"Ghosts / Spirits"},
    {"id": 76 , "ru":"Путешествие во времени", "en":"Time travel"},
    {"id": 77 , "ru":"Рабы", "en":"Slaves"},
    {"id": 78 , "ru":"Разумные расы", "en":"Intelligent races"},
    {"id": 79 , "ru":"Ранги силы", "en":"Power ranks"},
    {"id": 80 , "ru":"Реинкарнация", "en":"Reincarnation"},
    {"id": 81 , "ru":"Роботы", "en":"Robots"},
    {"id": 82 , "ru":"Рыцари ", "en":"Knights"},
    {"id": 83 , "ru":"Самураи", "en":"Samurai"},
    {"id": 84 , "ru":"Система", "en":"System"},
    {"id": 85 , "ru":"Скрытие личности", "en":"Identity hiding"},
    {"id": 86 , "ru":"Спасение мира", "en":"Saving the world"},
    {"id": 87 , "ru":"Спортивное тело", "en":"Sports body"},
    {"id": 88 , "ru":"Средневековье", "en":"Middle Ages"},
    {"id": 89 , "ru":"Стимпанк", "en":"Steampunk"},
    {"id": 90 , "ru":"Супергерои", "en":"Superheroes"},
    {"id": 91 , "ru":"Традиционные игры", "en":"Traditional games"},
    {"id": 92 , "ru":"Умный ГГ", "en":"Smart MC"},
    {"id": 93 , "ru":"Учитель  / ученик", "en":"Teacher / student"},
    {"id": 94 , "ru":"Философия", "en":"Philosophy"},
    {"id": 95 , "ru":"Хиккикомори", "en":"Hikkikomori"},
    {"id": 96 , "ru":"Холодное оружие", "en":"Cold weapons"},
    {"id": 97 , "ru":"Шантаж", "en":"Blackmail"},
    {"id": 98 , "ru":"Эльфы", "en":"Elves"},
    {"id": 99 , "ru":"Якудза", "en":"Yakuza"},
    {"id": 100, "ru":"Яндере", "en":"Yandere"},
    {"id": 101, "ru":"Япония", "en":"Japan"},
]

genres = [
    {"id": 0 , "ru": "Арт", "en": "Art"},
    {"id": 1 , "ru": "Безумие", "en": "Madness"},
    {"id": 2 , "ru": "Боевик", "en": "Action"},
    {"id": 3 , "ru": "Боевые искусства", "en": "Martial arts"},
    {"id": 4 , "ru": "Вампиры", "en": "Vampires"},
    {"id": 5 , "ru": "Военное", "en": "War"},
    {"id": 6 , "ru": "Гарем", "en": "Harem"},
    {"id": 7 , "ru": "Гендерная интрига", "en": "Gender intrigue"},
    {"id": 8 , "ru": "Героическое фентези", "en": "Heroic fantasy"},
    {"id": 9 , "ru": "Демоны", "en": "Demons"},
    {"id": 10, "ru": "Детектив", "en": "Detective"},
    {"id": 11, "ru": "Детское", "en": "Children's"},
    {"id": 12, "ru": "Дзёсай", "en": "Josai"},
    {"id": 13, "ru": "Драма", "en": "Drama"},
    {"id": 14, "ru": "Игра", "en": "Game"},
    {"id": 15, "ru": "Исекай", "en": "Isekai"},
    {"id": 16, "ru": "История", "en": "History"},
    {"id": 17, "ru": "Киберпанк", "en": "Cyberpunk"},
    {"id": 18, "ru": "Кодомо", "en": "Kodomo"},
    {"id": 19, "ru": "Комедия", "en": "Comedy"},
    {"id": 20, "ru": "Космос", "en": "Space"},
    {"id": 21, "ru": "Магия", "en": "Magic"},
    {"id": 22, "ru": "Махо-сёдзё", "en": "Maho-shoujo"},
    {"id": 23, "ru": "Машины", "en": "Cars"},
    {"id": 24, "ru": "Меха", "en": "Mecha"},
    {"id": 25, "ru": "Мистика", "en": "Mysticism"},
    {"id": 26, "ru": "Музыка", "en": "Music"},
    {"id": 27, "ru": "Научная фантастика", "en": "Sci-fi"},
    {"id": 28, "ru": "Омегаверс", "en": "Omegaverse"},
    {"id": 29, "ru": "Пародия", "en": "Parody"},
    {"id": 30, "ru": "Повседневность", "en": "Everyday life"},
    {"id": 31, "ru": "Полиция", "en": "Police"},
    {"id": 32, "ru": "Постапокалиптика", "en": "Post-apocalyptic"},
    {"id": 33, "ru": "Приключения", "en": "Adventure"},
    {"id": 34, "ru": "Психология", "en": "Psychology"},
    {"id": 35, "ru": "Романтика", "en": "Romance"},
    {"id": 36, "ru": "Самурайский боевик", "en": "Samurai action"},
    {"id": 37, "ru": "Сверхъестественное", "en": "Supernatural"},
    {"id": 38, "ru": "Сёдзё", "en": "Shoujo"},
    {"id": 39, "ru": "Сёдзё-ай", "en": "Shoujo-ai"},
    {"id": 40, "ru": "Сёнен", "en": "Shonen"},
    {"id": 41, "ru": "Сёнен-ай", "en": "Shonen-ai"},
    {"id": 42, "ru": "Спорт", "en": "Sports"},
    {"id": 43, "ru": "Супер сила", "en": "Super power"},
    {"id": 44, "ru": "Сэйнен", "en": "Seinen"},
    {"id": 45, "ru": "Трагедия", "en": "Tragedy"},
    {"id": 46, "ru": "Триллер", "en": "Thriller"},
    {"id": 47, "ru": "Ужасы", "en": "Horror"},
    {"id": 48, "ru": "Фантастика", "en": "Sci-Fi"},
    {"id": 49, "ru": "Фэнтези", "en": "Fantasy"},
    {"id": 50, "ru": "Школа", "en": "School"},
    {"id": 51, "ru": "Этти", "en": "Ecchi"},
    {"id": 52, "ru": "Юри", "en": "Yuri"},
]

